# Generated by Django 4.2.3 on 2023-10-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_body_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
