# Generated by Django 4.2.3 on 2023-10-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='puissance',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
