# Generated by Django 4.2.3 on 2023-12-17 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_followers'),
        ('posts', '0011_post_report_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='report_number',
        ),
        migrations.AddField(
            model_name='post',
            name='reported',
            field=models.ManyToManyField(blank=True, related_name='reports', to='profiles.profile'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
