# Generated by Django 4.2.3 on 2023-12-23 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_post_report_number_post_reported_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='in_response_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment'),
        ),
    ]
