# Generated by Django 4.2.3 on 2023-12-23 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_comment_in_response_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='in_response_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_post',
            field=models.BooleanField(default=True),
        ),
    ]
