# Generated by Django 4.2.3 on 2023-12-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_in_response_to_post_is_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.choice'),
        ),
    ]
