# Generated by Django 4.2.3 on 2023-12-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='parent_categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.choice'),
        ),
    ]
