# Generated by Django 4.2.3 on 2023-12-23 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_choice_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='parent_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.choice'),
        ),
    ]
