# Generated by Django 4.2.3 on 2023-12-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_choice_parent_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.choice'),
        ),
    ]
