# Generated by Django 4.2.5 on 2024-03-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0024_alter_choice_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="puissance",
            field=models.IntegerField(default=0),
        ),
    ]
