# Generated by Django 4.2.5 on 2024-03-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0025_like_puissance"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="campus",
            field=models.CharField(
                choices=[
                    ("Saclay", "Saclay"),
                    ("Rennes", "Rennes"),
                    ("Metz", "Metz"),
                    ("--", "--"),
                ],
                default="--",
                max_length=10,
            ),
        ),
    ]
