# Generated by Django 4.2.5 on 2024-05-23 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0012_profile_assos"),
        ("posts", "0028_alter_post_campus"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="association",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.association",
            ),
        ),
    ]
