# Generated by Django 4.2.5 on 2024-06-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0029_post_association"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_troll",
            field=models.BooleanField(default=False),
        ),
    ]
