# Generated by Django 4.2.5 on 2024-06-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0031_alter_post_in_response_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="treated",
            field=models.BooleanField(default=False),
        ),
    ]
