# Generated by Django 4.2.3 on 2023-12-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('administration', 'Administration'), ('association', 'Association'), ('convention', 'Soirée Convention Étudiante')], default='etudiant', max_length=50),
        ),
    ]
