# Generated by Django 4.2.5 on 2024-05-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0010_profile_display_site_explanation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Association",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="relationship",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="relationship",
            name="sender",
        ),
        migrations.AddField(
            model_name="profile",
            name="promo",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Relationship",
        ),
    ]
