# Generated by Django 4.2.5 on 2024-05-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0011_association_remove_relationship_receiver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="assos",
            field=models.ManyToManyField(blank=True, to="profiles.association"),
        ),
    ]
