# Generated by Django 4.2.5 on 2024-05-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0012_profile_assos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="country",
        ),
        migrations.AddField(
            model_name="profile",
            name="pseudo",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
