# Generated by Django 5.0.2 on 2024-03-24 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0010_profile_display_site_explanation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwipePossibleAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SwipeQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('question', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('short', 'Réponse courte'), ('long', 'Réponse longue'), ('binary', 'Question binaire'), ('multiple', 'Choix multiple'), ('radio', 'Choix unique'), ('scale', 'Échelle')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SwipeAnswerUser',
            fields=[
                ('answer_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swipe_survey.swipepossibleanswer')),
            ],
        ),
        migrations.AddField(
            model_name='swipepossibleanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swipe_survey.swipequestion'),
        ),
        migrations.CreateModel(
            name='SwipeSurvey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date_open', models.DateTimeField(default=None, null=True)),
                ('date_close', models.DateTimeField(default=None, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.AddField(
            model_name='swipequestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swipe_survey.swipesurvey'),
        ),
        migrations.AddConstraint(
            model_name='swipeansweruser',
            constraint=models.UniqueConstraint(fields=('answer', 'profile'), name='unique_answer_from_user'),
        ),
        migrations.AddConstraint(
            model_name='swipepossibleanswer',
            constraint=models.UniqueConstraint(fields=('question', 'content'), name='unique_possible_answer_in_question'),
        ),
        migrations.AddConstraint(
            model_name='swipequestion',
            constraint=models.UniqueConstraint(fields=('survey', 'position'), name='unique_position_in_survey'),
        ),
    ]
