# Generated by Django 5.0.2 on 2024-03-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swipe_survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipesurvey',
            name='description',
            field=models.TextField(default='Ceci est une super description !', max_length=500),
            preserve_default=False,
        ),
    ]
